name: Build FFmpeg with NVENC

on:
  workflow_dispatch:
    inputs:
      ffmpeg_version:
        description: 'FFmpeg version'
        required: true
        default: '6.1.2'
      nvenc_version:
        description: 'NVIDIA SDK version'
        required: true
        default: '12.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.6.0

      - name: Set up build environment
        run: sudo chmod +x build.sh

      - name: Build FFmpeg
        run: sudo ./build.sh ${{ github.event.inputs.ffmpeg_version }} ${{ github.event.inputs.nvenc_version }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ffmpeg-${{ github.event.inputs.ffmpeg_version }}-nvenc-${{ github.event.inputs.nvenc_version }}
          path: /tmp/bin/*.tar
          retention-days: 5
