name: Build FFmpeg with NVENC

on:
  workflow_dispatch:
    inputs:
      ffmpeg_version:
        description: 'FFmpeg version'
        required: true
        default: '6.1.2'
      nvenc_version:
        description: 'NVIDIA SDK version'
        required: true
        default: '12.0'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12
      options: --privileged

    permissions:
      contents: read
      packages: read
      actions: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up build environment
        run: |
          apt-get update
          apt-get install -y sudo git
          chmod +x build.sh
          mkdir -p /github/home

      - name: Build FFmpeg
        run: sudo ./build.sh ${{ github.event.inputs.ffmpeg_version }} ${{ github.event.inputs.nvenc_version }}

      - name: Prepare artifacts
        run: |
          mkdir -p /github/home/artifacts
          cp /tmp/bin/ffmpeg-${{ github.event.inputs.ffmpeg_version }}-nvenc-${{ github.event.inputs.nvenc_version }}.tar /github/home/artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ github.event.inputs.ffmpeg_version }}-nvenc-${{ github.event.inputs.nvenc_version }}
          path: /github/home/artifacts/*.tar
