name: FFmpeg Nvenc Build
on:
  push:
    branches:
      - master
      - main
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    #
    strategy:
      matrix:
        ffmpeg: ["5.1.2", "6.0"]
        nvenc: ["11.0", "11.1"]
    #
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      #
      - name: Build FFmpeg ${{ matrix.ffmpeg }} Nvenc ${{ matrix.nvenc }}
        id: build-ffmpeg-nvenc
        shell: bash
        run: |
          sudo sh build.sh ${{ matrix.ffmpeg}} ${{ matrix.nvenc }}
      #
      #- uses: montudor/action-zip@v1
      #  with:
      #    args: zip -qq -r ffmpeg-nvenc.zip /tmp/bin
      #
      - uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
         name: Upload-FFmpeg-${{ matrix.ffmpeg }}-Nvenc-${{ matrix.nvenc }}
         path: /tmp/bin/ffmpeg-ffprobe.zip
    #
  #
#
